version: '3.8'

services:
  rest-gateway:
    build: ./rest_gateway
    container_name: rest_gateway
    volumes:
      - ./playbooks:/app/playbooks
      - ./secrets:/app/secrets
    environment:
      - GCP_PROJECT_ID=your-project-id
    ports:
      - "5000:5000"
    restart: unless-stopped
