- name: Ensure USB payload directory exists
  file:
    path: "/usb-payloads/{{ client_name }}"
    state: directory
    mode: '0755'

- name: Copy client files to USB payload folder
  copy:
    src: "client-configs/{{ client_name }}/{{ item }}"
    dest: "/usb-payloads/{{ client_name }}/{{ item }}"
  loop:
    - ca.crt
    - client.crt
    - client.key
    - ta.key
    - "{{ client_name }}.ovpn"