---
- name: Ensure output directory exists
  file:
    path: "/factory_usb_output"
    state: directory
    mode: '0755'

- name: Download client config from GCP Secret Manager
  command: >
    gcloud secrets versions access latest
    --secret="vpn-client-{{ client_name }}"
  register: vpn_secret_content

- name: Save .ovpn config to disk
  copy:
    content: "{{ vpn_secret_content.stdout }}"
    dest: "/factory_usb_output/{{ client_name }}.ovpn"
    mode: '0600'
