- name: Fetch .ovpn config from GCP Secret Manager
  google.cloud.gcp_secretmanager_secret_version_info:
    project: "{{ gcp_project }}"
    secret: "vpn-client-{{ client_name }}"
    version: "latest"
  register: ovpn_secret

- name: Write .ovpn config to /tmp
  copy:
    content: "{{ ovpn_secret.payload.data | b64decode }}"
    dest: "/tmp/{{ client_name }}.ovpn"
    mode: '0644'

- name: Create USB install directory
  file:
    path: "/tmp/usb_{{ client_name }}"
    state: directory
    mode: '0755'

- name: Copy .ovpn to USB dir
  copy:
    src: "/tmp/{{ client_name }}.ovpn"
    dest: "/tmp/usb_{{ client_name }}/{{ client_name }}.ovpn"
    remote_src: yes

- name: Generate install.sh from template
  template:
    src: install.sh.j2
    dest: "/tmp/usb_{{ client_name }}/install.sh"
    mode: '0755'
