---
# tasks/activate_gcp_account.yaml
- name: Check that gcloud CLI is available
  command: which gcloud
  become: false
  register: gcloud_check
  failed_when: gcloud_check.rc != 0
  changed_when: false
  delegate_to: localhost
  run_once: true

- name: Activate GCP service account
  command: >
    gcloud auth activate-service-account
    --key-file="{{ gcp_credentials_file }}"
    --project="{{ gcp_project_id }}"
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: "{{ gcp_credentials_file }}"
  become: false
  delegate_to: localhost
  run_once: true

- name: Verify correct account is active
  command: gcloud auth list --filter=status:ACTIVE --format='value(account)'
  register: gcloud_active_account
  failed_when: gcloud_active_account.stdout != gcp_service_account
  become: false
  delegate_to: localhost
  run_once: true
