- name: Download VPN bundle from Secret Manager
  gcp_secret_manager_secret_info:
    name: "{{ gcp_secrets_prefix }}{{ client_name }}"
    project: "{{ gcp_project_id }}"
  register: vpn_bundle

- name: Write archive to temp file
  become: true
  copy:
    dest: "/tmp/{{ client_name }}.tar.gz"
    content: "{{ vpn_bundle.payload.data | b64decode }}"
    mode: '0600'
