---
# roles/vpn_client/tasks/download.yaml
- name: Set archive path
  set_fact:
    archive_path: "/tmp/client-configs/{{ client_name }}.tar.gz"

- name: Ensure /tmp/client-configs exists
  file:
    path: "/tmp/client-configs"
    state: directory
    mode: '0755'
  delegate_to: localhost

- name: Download base64 archive from GCP Secret Manager
  shell: |
    gcloud secrets versions access latest \
      --secret="vpn-client-{{ client_name }}" \
      --project="{{ gcp_project_id }}" > "{{ archive_path }}.b64"
  args:
    executable: /bin/bash
  register: gcloud_result
  failed_when: gcloud_result.rc != 0
  delegate_to: localhost

- name: Fail if downloaded base64 file is empty
  stat:
    path: "{{ archive_path }}.b64"
  register: archive_stat
  delegate_to: localhost

- name: Abort if base64 archive is empty
  fail:
    msg: "Downloaded base64 archive is empty."
  when: archive_stat.stat.size == 0
  delegate_to: localhost

- name: Decode base64 to tar.gz
  shell: |
    base64 -d "{{ archive_path }}.b64" > "{{ archive_path }}"
  args:
    executable: /bin/bash
  delegate_to: localhost

- name: Remove base64 file
  file:
    path: "{{ archive_path }}.b64"
    state: absent
  delegate_to: localhost

- debug:
    msg: "Archive ready at {{ archive_path }}"