- name: Ensure OpenVPN installed
  become: yes
  apt:
    name: openvpn
    state: present

- name: Upload client config
  become: yes
  copy:
    src: "client-configs/{{ client_name }}/{{ client_name }}.ovpn"
    dest: "/etc/openvpn/{{ client_name }}.ovpn"