# roles/vpn_client/tasks/install_from_secret.yaml
- name: Ensure gcloud CLI is available
  command: which gcloud
  register: gcloud_check
  failed_when: gcloud_check.rc != 0

- name: Create temp directory for install
  tempfile:
    state: directory
    suffix: vpnconfig
  register: temp_dir

- name: Download VPN archive from GCP Secret Manager
  shell: |
    gcloud secrets versions access latest \
      --secret="{{ gcp_secrets_prefix }}{{ client_name }}" \
      --project="{{ gcp_project_id }}" > {{ temp_dir.path }}/{{ client_name }}.tar.gz

- name: Extract archive
  unarchive:
    src: "{{ temp_dir.path }}/{{ client_name }}.tar.gz"
    dest: "{{ vpn_client_conf_dir }}/"
    remote_src: yes

- name: Restart OpenVPN
  systemd:
    name: openvpn-client@client
    enabled: yes
    state: restarted
