# roles/openvpn_client/tasks/install.yaml
- name: Copy .ovpn config to client
  copy:
    src: "secrets/{{ inventory_hostname }}.ovpn"
    dest: "/etc/openvpn/{{ inventory_hostname }}.conf"
    owner: root
    group: root
    mode: '0600'
