---
- name: Ensure OpenVPN client directory exists
  file:
    path: "/etc/openvpn/client"
    state: directory
    mode: '0755'

- name: Create temp dir for unpacking
  file:
    path: "/etc/openvpn/tmp_{{ client_name }}"
    state: directory
    mode: '0700'

- name: Extract client archive
  unarchive:
    src: "/tmp/{{ client_name }}.tar.gz"
    dest: "/etc/openvpn/tmp_{{ client_name }}"
    remote_src: true

- name: Backup previous client config (if exists)
  shell: |
    mkdir -p /etc/openvpn/backup_{{ client_name }}
    cp /etc/openvpn/client/{client.crt,client.key,ca.crt,ta.key,{{ client_name }}.ovpn} /etc/openvpn/backup_{{ client_name }}/ 2>/dev/null || true
  args:
    warn: false

- name: Replace certs and keys
  copy:
    src: "/etc/openvpn/tmp_{{ client_name }}/{{ item }}"
    dest: "/etc/openvpn/client/{{ item }}"
    remote_src: true
    mode: '0600'
  loop:
    - client.crt
    - client.key
    - ca.crt
    - ta.key
    - "{{ client_name }}.ovpn"

- name: Clean temp dir
  file:
    path: "/etc/openvpn/tmp_{{ client_name }}"
    state: absent

- name: Install DNS hook script
  copy:
    src: dns-hooks.sh
    dest: /etc/openvpn/dns-hooks.sh
    mode: '0755'

- name: Copy .ovpn config to systemd location
  copy:
    src: "/etc/openvpn/client/{{ client_name }}.ovpn"
    dest: "/etc/openvpn/{{ client_name }}.conf"
    mode: '0600'

- name: Reload OpenVPN client (if not passive)
  systemd:
    name: "openvpn-client@{{ client_name }}"
    enabled: true
    state: restarted
  when: not install_passive | default(false)
