---
# vpn_client/tasks/mark_installed.yaml
- name: Update metadata to mark installed
  delegate_to: localhost
  copy:
    dest: "{{ hostvars['localhost']['client_meta_dir'] }}/{{ inventory_hostname }}.yaml"
    content: |
      version: {{ client_meta.latest }}
      latest: {{ client_meta.latest }}
      installed: true
      pending_revoke: true

- name: Check if client metadata file exists
  delegate_to: localhost
  stat:
    path: "{{ hostvars['localhost']['client_meta_dir'] }}/{{ inventory_hostname }}.yaml"
  register: meta_check

- name: Generate initial client metadata if missing
  delegate_to: localhost
  copy:
    dest: "{{ hostvars['localhost']['client_meta_dir'] }}/{{ inventory_hostname }}.yaml"
    content: |
      version: "{{ lookup('pipe', 'date +%s') }}"
      latest: "{{ lookup('pipe', 'date +%s') }}"
      installed: false
      pending_revoke: false
  when: not meta_check.stat.exists

- name: Read client metadata from controller
  delegate_to: localhost
  slurp:
    src: "{{ hostvars['localhost']['client_meta_dir'] }}/{{ inventory_hostname }}.yaml"
  register: meta_raw

- set_fact:
    client_meta: "{{ meta_raw.content | b64decode | from_yaml }}"