---
# roles/vpn_client/tasks/mark_installed.yaml
- name: Update metadata to mark installed
  delegate_to: localhost
  copy:
    dest: "{{ client_meta_dir }}/{{ client_name  }}.yaml"
    content: |
      version: {{ client_meta.latest }}
      latest: {{ client_meta.latest }}
      installed: true
      pending_revoke: true
