- name: Read and encode archive
  delegate_to: localhost
  slurp:
    src: "{{ client_config_base_dir }}/{{ client_name }}.tar.gz"
  register: client_archive

- name: Upload archive to GCP Secret Manager
  gcp_secret:
    name: "{{ gcp_secrets_prefix }}{{ client_name }}"
    data: "{{ client_archive.content }}"
    state: present
    project: "{{ gcp_project_id }}"
