---
# roles/vpn_client/tasks/upload.yaml
- name: Ensure client_config_dir is defined
  set_fact:
    client_config_dir: "{{ client_configs_base_dir }}/{{ client_name }}"
  when: client_config_dir is not defined
  delegate_to: localhost

- name: Check if archive exists on controller
  delegate_to: localhost
  become: false
  stat:
    path: "{{ client_config_dir }}/{{ client_name }}.tar.gz"
  register: archive_check

- name: Abort if archive missing
  fail:
    msg: "Client archive not found: {{ client_config_dir }}/{{ client_name }}.tar.gz"
  when: not archive_check.stat.exists

- name: Ensure gcloud CLI is available
  delegate_to: localhost
  become: false
  command: which gcloud
  register: gcloud_path_check
  failed_when: gcloud_path_check.rc != 0
  changed_when: false

- name: Encode archive to base64
  delegate_to: localhost
  become: false
  shell: |
    base64 "{{ client_config_dir }}/{{ client_name }}.tar.gz" > "{{ client_config_dir }}/{{ client_name }}.b64"

- name: Upload to GCP Secret Manager using gcloud CLI (base64)
  delegate_to: localhost
  become: false
  shell: |
    gcloud secrets create {{ gcp_secrets_prefix }}{{ client_name }} \
      --data-file="{{ client_config_dir }}/{{ client_name }}.b64" \
      --replication-policy="automatic" \
      --project="{{ gcp_project_id }}" || \
    gcloud secrets versions add {{ gcp_secrets_prefix }}{{ client_name }} \
      --data-file="{{ client_config_dir }}/{{ client_name }}.b64" \
      --project="{{ gcp_project_id }}"
  register: gcloud_result
  retries: 3
  delay: 5

- name: Confirm upload complete
  become: false
  delegate_to: localhost
  debug:
    msg: "Uploaded {{ client_name }} archive to GCP Secret Manager ({{ gcp_secrets_prefix }}{{ client_name }})"
