- name: Read .ovpn file from disk
  slurp:
    src: "client-configs/{{ name }}/{{ name }}.ovpn"
  register: ovpn_data

- name: Create Secret for the client
  google.cloud.gcp_secretmanager_secret:
    name: "vpn-client-{{ name }}"
    project: "{{ gcp_project }}"
    replication:
      automatic: {}
    state: present

- name: Upload secret version with .ovpn data
  google.cloud.gcp_secretmanager_secret_version:
    secret: "vpn-client-{{ name }}"
    project: "{{ gcp_project }}"
    payload: "{{ ovpn_data.content | b64decode }}"
