---
# roles/vpn_client/tasks/upload.yaml
- name: Ensure required vars are present
  assert:
    that:
      - client_name is defined
      - client_config_dir is defined

- name: Ensure client archive exists
  stat:
    path: "{{ client_config_dir }}/{{ client_name }}.tar.gz"
  register: archive_check
  delegate_to: localhost

- name: Fail if archive missing
  fail:
    msg: "Missing client archive for {{ client_name }}"
  when: not archive_check.stat.exists

- name: Read and encode archive for GCP upload
  slurp:
    src: "{{ client_config_dir }}/{{ client_name }}.tar.gz"
  register: client_archive
  delegate_to: localhost

- name: Upload archive to GCP Secret Manager
  gcp_secret:
    name: "{{ gcp_secrets_prefix }}{{ client_name }}"
    data: "{{ client_archive.content }}"
    state: present
    project: "{{ gcp_project_id }}"
  register: upload_result
  retries: 3
  delay: 5

- debug:
    msg: "Uploaded archive for {{ client_name }} to GCP Secret Manager"
