---
# roles/vpn_client/tasks/upload.yaml
- name: Check if archive exists on controller
  delegate_to: localhost
  stat:
    path: "{{ client_config_dir }}/{{ client_name }}.tar.gz"
  register: archive_check

- name: Abort if archive missing
  fail:
    msg: "Client archive not found: {{ client_config_dir }}/{{ client_name }}.tar.gz"
  when: not archive_check.stat.exists

- name: Read and base64 encode archive
  delegate_to: localhost
  slurp:
    src: "{{ client_config_dir }}/{{ client_name }}.tar.gz"
  register: client_archive

- name: Upload to GCP Secret Manager
  google.cloud.gcp_secret:
    name: "{{ gcp_secrets_prefix }}{{ client_name }}"
    data: "{{ client_archive.content }}"
    state: present
    project: "{{ gcp_project_id }}"
  retries: 3
  delay: 5
  delegate_to: localhost
  register: gcp_result

- name: Confirm upload complete
  debug:
    msg: "Uploaded {{ client_name }} archive to GCP Secret Manager ({{ gcp_secrets_prefix }}{{ client_name }})"