- name: Upload to GCP Secret Manager
  gcp_secret:
    name: "{{ gcp_secrets_prefix }}{{ client_name }}"
    project: "{{ gcp_project_id }}"
    secret_data: "{{ lookup('file', 'client-configs/' + client_name + '/' + client_name + '.tar.gz') | b64encode }}"
    state: present
  delegate_to: localhost
