---
# roles/vpn_client/tasks/upload.yaml
- name: Check archive
  stat:
    path: "{{ client_config_dir }}/{{ client_name }}.tar.gz"
  delegate_to: localhost
  register: archive_check

- name: Fail if archive missing
  fail:
    msg: "Missing archive for {{ client_name }} in {{ client_config_dir }}"
  when: not archive_check.stat.exists

- name: Read archive
  slurp:
    src: "{{ client_config_dir }}/{{ client_name }}.tar.gz"
  delegate_to: localhost
  register: client_archive

- name: Upload to GCP Secret Manager
  gcp_secret:
    name: "{{ gcp_secrets_prefix }}{{ client_name }}"
    data: "{{ client_archive.content }}"
    state: present
    project: "{{ gcp_project_id }}"
  retries: 3
  delay: 5

- debug:
    msg: "Archive for {{ client_name }} uploaded to GCP"