---
# playbooks/tasks/client_flow.yaml
- name: Compute client_config_dir
  set_fact:
    client_config_dir: "{{ client_configs_base_dir }}/{{ client_name }}"
  delegate_to: localhost

- name: Show expected vars
  debug:
    msg:
      - "Client: {{ client_name }}"
      - "EasyRSA Dir: {{ easy_rsa_dir }}"
      - "Local Client Config Dir: {{ client_config_dir }}"

- name: Log static IP for client (if any)
  debug:
    msg: "Static IP for {{ client_name }} is {{ static_map[client_name] if static_map is defined and client_name in static_map else 'UNDEFINED' }}"

- name: Create client certificate
  block:
    - name: Run vpn_cert::create
      include_role:
        name: vpn_cert
        tasks_from: create
  rescue:
    - debug: msg="Failed to create certificate for {{ client_name }}"
    - meta: end_host

- name: Upload to GCP Secret Manager
  block:
    - name: Run vpn_client::upload
      include_role:
        name: vpn_client
        tasks_from: upload
  rescue:
    - debug: msg="Failed to upload archive for {{ client_name }}"
    - meta: end_host

- debug:
    msg: "Completed full onboarding for {{ client_name }}"