---
- name: Set client_name fact for current loop
  set_fact:
    client_name: "{{ item }}"

- name: Verify easy_rsa_dir is visible
  debug:
    var: easy_rsa_dir

- name: Create client certificate
  block:
    - name: Run vpn_cert::create with scoped vars
      include_role:
        name: vpn_cert
        tasks_from: create
      vars:
        easy_rsa_dir: "{{ easy_rsa_dir }}"
  rescue:
    - debug: msg="Failed to create certificate for {{ client_name }}"
    - meta: end_host

- name: Upload to GCP Secret Manager
  block:
    - name: Run vpn_client::upload with scoped vars
      include_role:
        name: vpn_client
        tasks_from: upload
      vars:
        gcp_project_id: "{{ gcp_project_id }}"
        gcp_secrets_prefix: "{{ gcp_secrets_prefix }}"
        client_config_base_dir: "{{ client_config_base_dir }}"
  rescue:
    - debug: msg="Failed to upload archive for {{ client_name }}"
    - meta: end_host

- debug:
    msg: "Completed full client onboarding for {{ client_name }}"
