---
- name: Set client_name fact for current loop
  set_fact:
    client_name: "{{ item }}"

- name: Create client certificate
  block:
    - include_role:
        name: vpn_cert
        tasks_from: create
  rescue:
    - debug: msg="Failed to create certificate for {{ client_name }}"
    - meta: end_host

- name: Upload to Secret Manager
  block:
    - include_role:
        name: vpn_client
        tasks_from: upload
  rescue:
    - debug: msg="Failed to upload archive for {{ client_name }}"
    - meta: end_host

- debug:
    msg: "Completed full client onboarding for {{ client_name }}"
