---
- name: Set client_name fact for current loop
  set_fact:
    client_name: "{{ item }}"

- name: Show expected vars
  debug:
    msg:
      - "Client: {{ client_name }}"
      - "EasyRSA Dir: {{ easy_rsa_dir | default('not defined') }}"
      - "Client Config Base Dir: /home/kharkov501/client-configs/{{ client_name }}"

- name: Create client certificate
  block:
    - name: Run vpn_cert::create with var injection
      include_role:
        name: vpn_cert
        tasks_from: create
      vars:
        client_config_base_dir: "/home/kharkov501/client-configs/{{ client_name }}"
  rescue:
    - debug: msg="Failed to create certificate for {{ client_name }}"
    - meta: end_host

- name: Upload to GCP Secret Manager
  block:
    - name: Run vpn_client::upload
      include_role:
        name: vpn_client
        tasks_from: upload
  rescue:
    - debug: msg="Failed to upload archive for {{ client_name }}"
    - meta: end_host

- debug:
    msg: "Completed full client onboarding for {{ client_name }}"
