---
- name: Set per-client local config directory
  set_fact:
    client_config_dir: "{{ client_configs_base_dir }}/{{ client_name }}"

- name: Show expected vars
  debug:
    msg:
      - "Client: {{ client_name }}"
      - "EasyRSA Dir: {{ easy_rsa_dir }}"
      - "Local Client Config Dir: {{ client_config_dir }}"

- name: Create client certificate
  block:
    - name: Run vpn_cert::create
      include_role:
        name: vpn_cert
        tasks_from: create
      vars:
        client_config_dir: "{{ client_config_dir }}"
  rescue:
    - debug: msg="Failed to create certificate for {{ client_name }}"
    - meta: end_host

- name: Upload to GCP Secret Manager
  block:
    - name: Run vpn_client::upload
      include_role:
        name: vpn_client
        tasks_from: upload
      vars:
        client_config_dir: "{{ client_config_dir }}"
  rescue:
    - debug: msg="Failed to upload archive for {{ client_name }}"
    - meta: end_host

- debug:
    msg: "Completed full onboarding for {{ client_name }}"
