---
# tasks/client_flow.yaml
- name: Set client-specific path
  set_fact:
    client_config_base_dir: "/home/kharkov501/client-configs/{{ client_name }}"

- name: Show expected vars
  debug:
    msg:
      - "Client: {{ client_name }}"
      - "EasyRSA Dir: {{ easy_rsa_dir | default('not defined') }}"
      - "Config Path: {{ client_config_base_dir }}"

- name: Create client certificate
  block:
    - name: Run vpn_cert::create
      include_role:
        name: vpn_cert
        tasks_from: create
      vars:
        client_name: "{{ client_name }}"
        client_config_base_dir: "{{ client_config_base_dir }}"
        easy_rsa_dir: "{{ easy_rsa_dir }}"
  rescue:
    - debug: msg="Failed to create certificate for {{ client_name }}"
    - meta: end_host

- name: Upload to GCP Secret Manager
  block:
    - name: Run vpn_client::upload
      include_role:
        name: vpn_client
        tasks_from: upload
      vars:
        client_name: "{{ client_name }}"
        client_config_base_dir: "{{ client_config_base_dir }}"
        gcp_secrets_prefix: "{{ gcp_secrets_prefix }}"
        gcp_project_id: "{{ gcp_project_id }}"
  rescue:
    - debug: msg="Failed to upload archive for {{ client_name }}"
    - meta: end_host

- debug:
    msg: "Completed full client onboarding for {{ client_name }}"