---
# playbooks/tasks/client_flow.yaml
- name: Set client local config dir (Ansible Hub)
  delegate_to: localhost
  set_fact:
    client_config_dir: "{{ client_configs_base_dir }}/{{ client_name }}"

- name: Show vars
  debug:
    msg:
      - "Client: {{ client_name }}"
      - "EasyRSA Dir: {{ easy_rsa_dir }}"
      - "Local Client Config Dir: {{ client_config_dir }}"

- name: Run vpn_cert::create
  include_role:
    name: vpn_cert
    tasks_from: create
  vars:
    client_config_dir: "{{ client_config_dir }}"

- name: Run vpn_client::upload
  include_role:
    name: vpn_client
    tasks_from: upload
  vars:
    client_config_dir: "{{ client_config_dir }}"
