- name: Ensure CCD directory exists
  file:
    path: /etc/openvpn/ccd
    state: directory
    mode: '0755'
  become: true

- name: Assign static IP to client via CCD
  copy:
    dest: "/etc/openvpn/ccd/{{ client_name }}"
    content: "ifconfig-push {{ assigned_ip }} 255.255.255.0\n"
    mode: '0644'
  become: true
