- name: Ensure CCD directory exists
  file:
    path: "{{ openvpn_config_dir }}/ccd"
    state: directory
    mode: '0755'

- name: Write static IP mappings for each client
  copy:
    dest: "{{ openvpn_config_dir }}/ccd/{{ item.key }}"
    content: "ifconfig-push {{ item.value }} 255.255.255.0\n"
    mode: '0644'
  loop: "{{ static_map | dict2items }}"

- name: Reload OpenVPN
  systemd:
    name: openvpn-server@server
    state: reloaded
  notify: Restart OpenVPN
  when: reload_openvpn | default(true)
