---
- name: Create and upload one or multiple VPN clients
  hosts: vpn
  gather_facts: false

  vars_files:
    - group_vars/vpn.yaml

  tasks:
    - name: Ensure client_names are provided
      assert:
        that:
          - client_names is defined
          - client_names | length > 0
        fail_msg: "Provide client names via -e 'client_names=[\"client1\", \"client2\"]'"

    - name: Create/upload for each client
      include_tasks: tasks/client_flow.yaml
      loop: "{{ client_names }}"
      loop_control:
        loop_var: client_name
