---
- name: Create and upload one or multiple VPN clients
  hosts: vpn
  gather_facts: false
  vars:
    client_names: []
    vpn_action: "create"

  pre_tasks:
    - name: Ensure client_names are provided
      fail:
        msg: "client_names must be passed using -e"
      when: client_names is not defined or client_names | length == 0

  tasks:
    - name: Create/upload for each client
      include_role:
        name: vpn_cert
      loop: "{{ client_names }}"
      loop_control:
        loop_var: client_name
      vars:
        client_name: "{{ client_name }}"
