---
# playbooks/create_and_upload.yaml
- name: Create and upload one or multiple VPN clients
  hosts: vpn
  gather_facts: false

  pre_tasks:
    - name: Ensure client_names are provided
      assert:
        that:
          - client_names is defined
          - client_names | length > 0
        fail_msg: "Provide client names via -e 'client_names=[\"client1\"]'"

    - import_tasks: ../tasks/load_controller_vars.yaml

    - name: Parse static_map if it's a JSON string
      set_fact:
        static_map: "{{ static_map | from_json }}"
      when: static_map is defined and static_map is string and static_map | regex_search('^{.*}$')

    - name: Normalize static_map if it's a dict
      set_fact:
        static_map: >-
          {{
            static_map | dict2items
            | map('combine', [{'key': item.key|string, 'value': item.value}] )
            | list | items2dict
          }}
      when: static_map is defined and static_map is not string

  tasks:
    - name: Create/upload for each client
      include_tasks: tasks/client_flow.yaml
      loop: "{{ client_names }}"
      loop_control:
        loop_var: client_name
