---
- name: Create and upload one or multiple VPN clients
  hosts: vpn_node
  become: true
  gather_facts: true

  vars:
    client_names: "{{ client_names }}"

  tasks:
    - name: Create/upload for each client
      include_tasks: tasks/client_flow.yaml
      loop: "{{ client_names }}"
      loop_control:
        loop_var: client_name
      vars:
        client_name: "{{ client_name }}"
        easy_rsa_dir: "{{ easy_rsa_dir }}"
        openvpn_config_dir: "{{ openvpn_config_dir }}"
        gcp_project_id: "{{ gcp_project_id }}"
        gcp_secrets_prefix: "{{ gcp_secrets_prefix }}"
        secret_location: "{{ secret_location }}"
