---
# playbooks/create_and_upload.yaml
- name: Create and upload one or multiple VPN clients
  hosts: vpn
  gather_facts: false

  pre_tasks:
    - name: Ensure client_names are provided
      assert:
        that:
          - client_names is defined
          - client_names | length > 0
        fail_msg: "Provide client names via -e 'client_names=[\"client1\"]'"

    - import_tasks: ../tasks/load_controller_vars.yaml

    - name: Generate static_map from client_names and base_ip
      set_fact:
        static_map: >-
          {{
            dict(client_names | zip(
              range(base_ip | ansible.utils.ipaddr('int'),
                    (base_ip | ipaddr('int')) + client_names | length)
              | map('int') | map('community.general.ipaddr') | list))
          }}
      vars:
        base_ip: "10.9.0.30"

  tasks:
    - name: Provision each client
      include_tasks: tasks/client_flow.yaml
      loop: "{{ client_names }}"
      loop_control:
        loop_var: client_name
      vars:
        client_static_ip: "{{ static_map[client_name] }}"