---
- name: Create and upload one or multiple VPN clients
  hosts: vpn_node
  vars:
    client_names: []  # Example: -e 'client_names=["client101","client102"]'
  tasks:
    - name: Create/upload for each client
      include_tasks: tasks/client_flow.yaml
      loop: "{{ client_names }}"
      loop_control:
        loop_var: client_name