---
# playbooks/create_and_upload.yaml
- name: Create and upload one or multiple VPN clients
  hosts: vpn
  gather_facts: false

  pre_tasks:
    - name: Ensure client_names are provided
      assert:
        that:
          - client_names is defined
          - client_names | length > 0

    - import_tasks: ../tasks/load_controller_vars.yaml

    - name: Build static_map from clients.yaml
      set_fact:
        static_map: "{{ lookup('vars', 'clients') }}"
      vars_files:
        - "../group_vars/vpn/clients_index.yaml"

  tasks:
    - name: Set client_static_ip and include onboarding logic
      include_tasks: tasks/client_flow.yaml
      loop: "{{ client_names }}"
      loop_control:
        loop_var: client_name
      vars:
        client_static_ip: "{{ static_map[client_name] }}"