---
- name: Create and upload one or multiple VPN clients
  hosts: vpn_node
  become: true
  gather_facts: true

  vars:
    client_names: "{{ client_names }}"

  tasks:
    - name: Create/upload for each client
      include_tasks: tasks/client_flow.yaml
      loop: "{{ client_names }}"
      loop_control:
        loop_var: single_client_name
      vars:
        client_name: "{{ single_client_name }}"
