- name: Create and upload VPN client
  hosts: vpn_group
  gather_facts: false
  vars:
    client_name: "{{ client_name }}"
    vpn_action: create
  roles:
    - role: vpn_cert
    - role: vpn_client
      tasks_from: upload