- name: Deactivate and clean up VPN client
  hosts: vpn_group
  gather_facts: false
  vars:
    client_name: "{{ client_name }}"
    action: revoke
  roles:
    - role: vpn_cert
    - role: vpn_client
      tasks_from: delete