---
# playbooks/delete_clients.yaml
- name: Deactivate and delete one or more VPN clients
  hosts: vpn
  gather_facts: false

  pre_tasks:
    - name: Ensure client_names are provided
      fail:
        msg: "client_names must be passed using -e"
      when: client_names is not defined or client_names | length == 0

    - name: Load controller vars for delegated localhost
      include_vars:
        file: "host_vars/localhost.yaml"
      delegate_to: localhost
      run_once: true

  tasks:
    - name: Deactivate and delete client
      include_tasks: ../roles/vpn_client/tasks/delete.yaml
      loop: "{{ client_names }}"
      loop_control:
        loop_var: client_name