---
# playbooks/delete_clients.yaml
# 1. Load controller-local vars via localhost
- name: Load vars for delegated localhost
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set controller vars as facts
      set_fact:
        gcp_secrets_prefix: "{{ gcp_secrets_prefix }}"
        gcp_project_id: "{{ gcp_project_id }}"
        client_configs_base_dir: "{{ client_configs_base_dir }}"
      when:
        - gcp_secrets_prefix is defined
        - gcp_project_id is defined
        - client_configs_base_dir is defined

# 2. Main deletion tasks for VPN clients
- name: Deactivate and delete one or more VPN clients
  hosts: vpn
  gather_facts: false

  pre_tasks:
    - name: Ensure client_names are provided
      fail:
        msg: "client_names must be passed using -e"
      when: client_names is not defined or client_names | length == 0

  tasks:
    - name: Deactivate and delete client
      include_tasks: ../roles/vpn_client/tasks/delete.yaml
      loop: "{{ client_names }}"
      loop_control:
        loop_var: client_name
