---
# playbooks/delete_clients.yaml
- name: Load controller (localhost) vars
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set controller vars as facts globally
      set_fact:
        gcp_project_id: "{{ gcp_project_id }}"
        gcp_secrets_prefix: "{{ gcp_secrets_prefix }}"
        client_configs_base_dir: "{{ client_configs_base_dir }}"
      when: gcp_project_id is defined

- name: Deactivate and delete one or more VPN clients
  hosts: vpn
  gather_facts: false

  pre_tasks:
    - name: Ensure client_names are provided
      fail:
        msg: "client_names must be passed using -e"
      when: client_names is not defined or client_names | length == 0

  tasks:
    - name: Deactivate and delete client
      include_tasks: ../roles/vpn_client/tasks/delete.yaml
      loop: "{{ client_names }}"
      loop_control:
        loop_var: client_name

