- name: Pull config from Secret Manager to factory
  hosts: localhost
  gather_facts: false
  vars:
    client_name: "{{ client_name }}"
    vpn_action: download
  roles:
    - role: vpn_client
    - role: factory_usb