---
# playbooks/factory_pull.yaml
- name: Factory pull of VPN config
  hosts: localhost
  gather_facts: false

  vars:
    output_dir: "/factory_output/{{ client_name }}"

  pre_tasks:
    - name: Ensure client_name is provided
      fail:
        msg: "client_name must be passed with -e client_name=NAME"
      when: client_name is not defined or client_name | length == 0

  tasks:
    - name: Download and extract client config from GCP Secret Manager
      include_role:
        name: vpn_client
        tasks_from: download

    - name: Copy extracted config to factory output directory
      copy:
        src: "{{ factory_client_config_dir }}/{{ client_name }}/"
        dest: "{{ output_dir }}/"
        mode: '0644'
        remote_src: yes

    - name: Render install.sh into factory config dir
      template:
        src: install.sh.j2
        dest: "{{ output_dir }}/install.sh"
        mode: '0755'

    - name: Confirm USB-ready config folder created
      debug:
        msg: "VPN config + installer ready at {{ output_dir }}"
