---
# playbooks/factory_pull.yaml
- name: Factory pull of VPN config
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: Ensure client_name is provided
      fail:
        msg: "client_name must be passed with -e client_name=NAME"
      when: client_name is not defined or client_name | length == 0

    - name: Load all group vars for delegated localhost
      include_vars: ../group_vars/all.yaml
      delegate_to: localhost
      run_once: true

  tasks:
    - name: Download and extract client config from GCP Secret Manager
      include_role:
        name: vpn_client
        tasks_from: download