- name: Create VPN cert and upload to GCP (on hub)
  hosts: localhost
  gather_facts: false
  vars:
    name: "{{ name }}"
  roles:
    - role: vpn_cert
      tasks_from: create
    - role: vpn_client
      tasks_from: upload

- name: Install VPN on client
  hosts: "{{ name }}"
  become: true
  vars:
    name: "{{ name }}"
  roles:
    - role: vpn_client
      tasks_from: install
