- name: Create, upload, and install VPN
  hosts: localhost
  gather_facts: false
  vars:
    client_name: "{{ client_name }}"
  roles:
    - vpn_cert/create
    - vpn_cert/upload

- name: Install VPN on client
  hosts: "{{ client_name }}"
  become: yes
  gather_facts: yes
  roles:
    - vpn_client/install
