- name: Create and provision new VPN client
  hosts: all
  gather_facts: no
  vars:
    vpn_client_name: "{{ inventory_hostname }}"
  tasks:
    - name: Generate VPN certificate
      import_role:
        name: vpn_cert
      tasks_from: create

    - name: Upload VPN client config to GCP Secret Manager
      import_role:
        name: gcp_secret_sync
      tasks_from: upload

    - name: Pull client config from GCP
      import_role:
        name: vpn_client
      tasks_from: install

    - name: Start VPN client
      import_role:
        name: vpn_client
      tasks_from: start
