- name: Onboard new VPN clients
  hosts: clients
  gather_facts: no

  tasks:
    - import_role:
        name: vpn_cert
        tasks_from: create

    - import_role:
        name: openvpn_client
        tasks_from: install

    - import_role:
        name: openvpn_client
        tasks_from: start

    - import_role:
        name: secret_sync
