---
- name: Install VPN config on client from Secret Manager
  hosts: vpn
  gather_facts: false

  vars:
    vpn_client_action: install
    client_name: "{{ client_name }}"

  roles:
    - vpn_client
