- name: Revoke cert and delete secret (on hub only)
  hosts: localhost
  gather_facts: false
  vars:
    name: "{{ name }}"
  roles:
    - role: vpn_cert
      tasks_from: revoke
    - role: vpn_client
      tasks_from: delete
