---
- name: Rotate and upload new cert for one or more clients
  hosts: vpn_group
  gather_facts: false
  vars:
    client_names: []

  pre_tasks:
    - name: Ensure client_names are provided
      fail:
        msg: "client_names must be passed using -e"
      when: client_names is not defined or client_names | length == 0

  tasks:
    - name: Set current client name
      set_fact:
        client_name: "{{ item }}"
      loop: "{{ client_names }}"
      loop_control:
        loop_var: item

    - name: Rotate cert
      include_role:
        name: vpn_cert
        tasks_from: rotate

    - name: Upload new archive
      include_role:
        name: vpn_client
        tasks_from: upload

    - debug:
        msg: "Rotated and reuploaded VPN client {{ client_name }}"
