---
- name: Rotate VPN cert and upload new config to Secret Manager
  hosts: localhost
  gather_facts: false

  vars:
    vpn_action: rotate
    client_name: "{{ client_name }}"

  roles:
    - vpn_cert
