- name: Rotate and re-upload VPN cert
  hosts: vpn_node
  become: true

  roles:
    - role: vpn_cert
      vars:
        client_task: rotate

    - role: vpn_client
      vars:
        client_task: upload
