# roles/vpn_cert/tasks/revoke.yaml
- name: Revoke client certificate
  command: "easyrsa revoke {{ client_name }}"
  args:
    chdir: "{{ easy_rsa_dir }}"
  delegate_to: vpn

- name: Update CRL
  command: "easyrsa gen-crl"
  args:
    chdir: "{{ easy_rsa_dir }}"
  delegate_to: vpn
